---
name: Build python

on:  # yamllint disable-line rule:truthy
  push:
    branches: [master, dev]
  pull_request:
    branches: [master, dev]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          make setup
      - name: Lint
        run: |
          make lint
      - name: Run unit tests
        run: |
          make unit
      - name: Run all
        run: |
          make all
